# This is github-action CI pipeline for recommendation-micro-service

name: Recommendation Micro Service CI
on: 
   push:
     branches:
        - main
     paths:
       - src/recommendation/**
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Install Docker
        uses: docker/setup-buildx-action@v1 

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: src/recommendation
          file: src/recommendation/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/recommendation-micro-service:${{ github.run_id }}

  update-k8s:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/recommendation-micro-service:${{github.run_id}}|" kubernetes/recommendation/deploy.yaml

      - name: Commit and Push Changes
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
          git add kubernetes/recommendation/deploy.yaml
          git commit -m "[Actions-CI]Update Kubernetes manifest"
          git push origin HEAD:main -f

